version: "3.9"

x-common-variables: &common-variables
  AMQP_URI: amqp://guest:guest@rabbitmq:5672/
  WAIT_HOSTS: "rabbitmq:5672"
  WAIT_HOSTS_TIMEOUT: 300
  WAIT_SLEEP_INTERVAL: 10
  WAIT_HOST_CONNECT_TIMEOUT: 30
  CONVERT_TO_WEBP_QUEUE: convert
  SEND_WEBP_TO_WHATSAPP_QUEUE: complete
  LOG_METRIC_QUEUE : metric
  LOG_LEVEL : info

services:
  whatsticker-master:
    build:
      context: "."
      dockerfile: ./master/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    command: bash -c "/wait && go run master/main.go -log-level DEBUG"
    volumes:
      - type: bind
        source: ./master/db
        target: /project/master/db
      - images:/project/master/images
      - videos:/project/master/videos
    environment:
      <<: *common-variables

  whatsticker-worker:
    build:
      context: "."
      dockerfile: ./worker/Dockerfile
    restart: always
    platform: linux/x86_64
    depends_on:
      - rabbitmq
    command: bash -c "/wait && go run worker/main.go"
    volumes:
      - images:/project/master/images
      - videos:/project/master/videos
    deploy:
      mode: replicated
      replicas: 3
    environment:
      <<: *common-variables
        
  whatsticker-logger:
    build:
      context: "."
      dockerfile: ./logger/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    command: bash -c "/wait && go run logger/main.go"
    environment:
      <<: *common-variables
    ports: 
      - "9091:9091"

  rabbitmq:
    restart: always
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - /var/lib/rabbitmq/
      - /var/log/rabbitmq/

volumes:
  images:
  videos:
